export const INSTITUTION_ADD_AGGREGATOR_INTEGRATION_BUTTON_TEXT = "ADD";

export const INSTITUTION_AGGREGATOR_INTEGRATION_FORM_AGGREGATOR_INSTITUTION_ID_LABEL_TEXT =
  "Aggregator Institution ID ";

export const INSTITUTION_ADD_AGGREGATOR_INTEGRATION_SUBMIT_BUTTON_TEXT = "SAVE";
