export const USER_ACCESS_TOKEN_ENV = "USER_ACCESS_TOKEN";
export const NO_WIDGET_PERMISSION_ACCESS_TOKEN_ENV =
  "NO_WIDGET_PERMISSION_ACCESS_TOKEN";
export const SUPER_USER_ACCESS_TOKEN_ENV = "SUPER_USER_ACCESS_TOKEN";
export const AGGREGATOR_USER_ACCESS_TOKEN_ENV = "AGGREGATOR_USER_ACCESS_TOKEN";
export const WIDGET_ACCESS_TOKEN = "WIDGET_ACCESS_TOKEN";
export const PERFORMANCE_SERVICE_ACCESS_TOKEN_ENV =
  "PERFORMANCE_SERVICE_ACCESS_TOKEN";
