export const INSTITUTIONS_ROUTE = "/institutions";
export const CACHE_LIST_CHILD_ROUTE = "/cacheList";

export const CACHE_LIST_ROUTE = `${INSTITUTIONS_ROUTE}${CACHE_LIST_CHILD_ROUTE}`;
export const PERFORMANCE_AUTH_ROUTE = "/performanceAuth";

export const AGGREGATOR_INSTITUTIONS_ROUTE = "/aggregatorInstitutions";
export const AGGREGATOR_INSTITUTIONS_SYNC_CHILD_ROUTE = "/sync";
export const AGGREGATOR_INSTITUTIONS_SYNC_ROUTE = `${AGGREGATOR_INSTITUTIONS_ROUTE}${AGGREGATOR_INSTITUTIONS_SYNC_CHILD_ROUTE}`;
