export const WIDGET_ACCESS_TOKEN = "WIDGET_ACCESS_TOKEN";
export const UCP_UI_USER_ACCESS_TOKEN = "UCP_UI_USER_ACCESS_TOKEN";
export const INSTITUTION_SERVICE_ACCESS_TOKEN =
  "INSTITUTION_SERVICE_ACCESS_TOKEN";
