name: Auth Rate-limit E2E

on: pull_request

jobs:
  setup-env:
    name: 'Load ENV Vars'
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit

  e2e-tests:
    name: Cypress
    runs-on: ubuntu-latest
    needs: [setup-env]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm ci

      - name: Cypress run (Rate-limiting)
        uses: cypress-io/github-action@v6
        env:
          RATE_LIMIT_TEST: true
        with:
          project: apps/authentication-service
          start: npm run dev --workspace apps/authentication-service
          wait-on: "http://localhost:8089/ping"
          spec: apps/authentication-service/cypress/e2e/**/rateLimiting.cy.ts

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/authentication-service/cypress/screenshots
