name: Auth Service E2E Tests

on: pull_request

jobs:
  setup-env:
    name: 'Load ENV Vars'
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit

  e2e-tests:
    name: Auth Cypress
    runs-on: ubuntu-latest
    needs: [setup-env]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm ci

      - name: 'Create env file'
        run: |
          ENV_FILE_PATH=./apps/authentication-service/.env
          touch ${ENV_FILE_PATH}
          
          # Vars
          echo -e "${{ needs.setup-env.outputs.env_vars }}" >> ${ENV_FILE_PATH}
          echo PORT="8089" >> ${ENV_FILE_PATH}
          
          # Secrets (can't load these from another job, due to GH security features)
          echo AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} >> ${ENV_FILE_PATH}          
          echo E2E_CLIENT_SECRET=${{ secrets.E2E_CLIENT_SECRET }} >> ${ENV_FILE_PATH}
          echo E2E_PASSWORD=${{ secrets.E2E_PASSWORD }} >> ${ENV_FILE_PATH}

          cat ${ENV_FILE_PATH}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: apps/authentication-service
          start: npm run dev --workspace apps/authentication-service
          wait-on: "http://localhost:${{ vars.PORT }}/ping"

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/authentication-service/cypress/screenshots
