name: Auth E2E (Rate-limit)

on: pull_request

jobs:
  setup-env:
    name: 'Load ENV Vars'
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit

  e2e-tests:
    name: "Cypress (Rate Limit)"
    runs-on: ubuntu-latest
    needs: [setup-env]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm ci

      - name: 'Create env file'
        run: |
          ENV_FILE_PATH=./apps/authentication-service/.env
          touch ${ENV_FILE_PATH}
          
          # Vars
          echo -e "${{ needs.setup-env.outputs.env_vars }}" >> ${ENV_FILE_PATH}
          
          # Secrets (can't load these from another job, due to GH security features)
          echo AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }} >> ${ENV_FILE_PATH}          
          echo E2E_CLIENT_SECRET=${{ secrets.E2E_CLIENT_SECRET }} >> ${ENV_FILE_PATH}
          echo AUTH_PASSWORD_WITH_KEY_ROLES=${{ secrets.AUTH_PASSWORD_WITH_KEY_ROLES }} >> ${ENV_FILE_PATH}
          echo AUTH_PASSWORD_WITHOUT_KEY_ROLES=${{ secrets.AUTH_PASSWORD_WITHOUT_KEY_ROLES }} >> ${ENV_FILE_PATH}
          
          cat ${ENV_FILE_PATH}

      - name: Start Institution Service
        run: npm run dev --workspace apps/institution-service

      - name: Cypress run (Standard suite)
        uses: cypress-io/github-action@v6
        with:
          project: apps/authentication-service
          start: npm run dev --workspace apps/authentication-service
          wait-on: "http://localhost:8089/ping", "http://localhost:8088/ping"
          spec: apps/authentication-service/cypress/e2e/**/!(rateLimiting.cy.ts)

      - name: Kill server # In order to reset rate-limiting
        run: kill $(lsof -t -i:8089)

      - name: Cypress run (Rate-limiting)
        uses: cypress-io/github-action@v6
        with:
          project: apps/authentication-service
          start: npm run dev:rate-limit --workspace apps/authentication-service
          wait-on: "http://localhost:8089/ping"
          spec: apps/authentication-service/cypress/e2e/**/rateLimiting.cy.ts

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/authentication-service/cypress/screenshots
