name: Performance E2E (General)

on: pull_request

jobs:
  e2e-tests:
    name: Cypress (Performance)
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      influxdb:
        image: influxdb:2.7
        env:
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: password
          INFLUXDB_HTTP_AUTH_ENABLED: "false" # Disables authentication
          INFLUXDB_ORG: ucp-org
          INFLUXDB_BUCKET: performance
          INFLUXDB_TOKEN: my-secret-token
        options: >-
          --health-cmd "curl --silent --fail http://localhost:8086/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8086:8086

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Setup InfluxDB Bucket & Org
        run: |
          curl -X POST http://localhost:8086/api/v2/setup \
            --header "Content-Type: application/json" \
            --data '{
              "username": "admin",
              "password": "password",
              "org": "ucp-org",
              "bucket": "performance",
              "token": "my-secret-token"
            }'

      - name: Seed Influx with Performance Data
        run: npm run test:seedInfluxPerformance --workspace apps/performance-service

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: apps/performance-service
          start: |
            npm run start --workspace apps/performance-service & sleep 10
            npm run dev:noRateLimiting --workspace apps/institution-service
          wait-on: "http://localhost:8088/ping, http://localhost:8090/ping"
          spec: apps/performance-service/cypress/e2e/general/*.cy.ts
        env:
          AUTH0_PERFORMANCE_CLIENT_SECRET: ${{ secrets.PERFORMANCE_SERVICE_CLIENT_SECRET }}
          REDIS_SERVER: redis://localhost:6379
          INFLUX_URL: http://localhost:8086
          EVENT_PROCESSING_TIME_LIMIT_SECONDS: 3
          POLL_INTERVAL_SECONDS: 1
          CYPRESS_WIDGET_CLIENT_ID: ${{ vars.WIDGET_CLIENT_ID }}
          CYPRESS_WIDGET_CLIENT_SECRET: ${{ secrets.WIDGET_CLIENT_SECRET }}
          CYPRESS_UCP_UI_USERNAME: ${{ vars.UCP_UI_USERNAME }}
          CYPRESS_UCP_UI_PASSWORD: ${{ secrets.UCP_UI_PASSWORD }}
          CYPRESS_WEB_UI_CLIENT_ID: ${{ vars.WEB_UI_CLIENT_ID }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/performance-service/cypress/screenshots
