name: UI E2E Tests

on: pull_request

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_auth_username_with_widget_role: ${{ secrets.AUTH_USERNAME_WITH_WIDGET_ROLE }}
          CYPRESS_auth_password_with_widget_role: ${{ secrets.AUTH_PASSWORD_WITH_WIDGET_ROLE }}
          CYPRESS_auth_username_without_widget_role: ${{ secrets.AUTH_USERNAME_WITHOUT_WIDGET_ROLE }}
          CYPRESS_auth_password_without_widget_role: ${{ secrets.AUTH_PASSWORD_WITHOUT_WIDGET_ROLE }}

        with:
          project: apps/ucp-ui
          start: npm run dev
          wait-on: "http://localhost:3000, http://localhost:8089/ping"

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/ucp-ui/cypress/screenshots
